# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-07-28 10:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户名', 'verbose_name_plural': '用户名'},
        ),
    ]
